/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as NestedRouteRouteImport } from './routes/nested/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NestedPikachuRouteImport } from './routes/nested/pikachu'
import { Route as NestedCharmanderRouteImport } from './routes/nested/charmander'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPokemonIndexRouteImport } from './routes/_authenticated/pokemon/index'
import { Route as AuthenticatedPokemonIdRouteImport } from './routes/_authenticated/pokemon/$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const NestedRouteRoute = NestedRouteRouteImport.update({
  id: '/nested',
  path: '/nested',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NestedPikachuRoute = NestedPikachuRouteImport.update({
  id: '/pikachu',
  path: '/pikachu',
  getParentRoute: () => NestedRouteRoute,
} as any)
const NestedCharmanderRoute = NestedCharmanderRouteImport.update({
  id: '/charmander',
  path: '/charmander',
  getParentRoute: () => NestedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPokemonIndexRoute =
  AuthenticatedPokemonIndexRouteImport.update({
    id: '/pokemon/',
    path: '/pokemon/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPokemonIdRoute = AuthenticatedPokemonIdRouteImport.update({
  id: '/pokemon/$id',
  path: '/pokemon/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nested': typeof NestedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/nested/charmander': typeof NestedCharmanderRoute
  '/nested/pikachu': typeof NestedPikachuRoute
  '/pokemon/$id': typeof AuthenticatedPokemonIdRoute
  '/pokemon/': typeof AuthenticatedPokemonIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nested': typeof NestedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/nested/charmander': typeof NestedCharmanderRoute
  '/nested/pikachu': typeof NestedPikachuRoute
  '/pokemon/$id': typeof AuthenticatedPokemonIdRoute
  '/pokemon': typeof AuthenticatedPokemonIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nested': typeof NestedRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/nested/charmander': typeof NestedCharmanderRoute
  '/nested/pikachu': typeof NestedPikachuRoute
  '/_authenticated/pokemon/$id': typeof AuthenticatedPokemonIdRoute
  '/_authenticated/pokemon/': typeof AuthenticatedPokemonIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/nested'
    | '/auth'
    | '/profile'
    | '/search'
    | '/settings'
    | '/nested/charmander'
    | '/nested/pikachu'
    | '/pokemon/$id'
    | '/pokemon/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/nested'
    | '/auth'
    | '/profile'
    | '/search'
    | '/settings'
    | '/nested/charmander'
    | '/nested/pikachu'
    | '/pokemon/$id'
    | '/pokemon'
  id:
    | '__root__'
    | '/'
    | '/nested'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/profile'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/nested/charmander'
    | '/nested/pikachu'
    | '/_authenticated/pokemon/$id'
    | '/_authenticated/pokemon/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NestedRouteRoute: typeof NestedRouteRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nested': {
      id: '/nested'
      path: '/nested'
      fullPath: '/nested'
      preLoaderRoute: typeof NestedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nested/pikachu': {
      id: '/nested/pikachu'
      path: '/pikachu'
      fullPath: '/nested/pikachu'
      preLoaderRoute: typeof NestedPikachuRouteImport
      parentRoute: typeof NestedRouteRoute
    }
    '/nested/charmander': {
      id: '/nested/charmander'
      path: '/charmander'
      fullPath: '/nested/charmander'
      preLoaderRoute: typeof NestedCharmanderRouteImport
      parentRoute: typeof NestedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pokemon/': {
      id: '/_authenticated/pokemon/'
      path: '/pokemon'
      fullPath: '/pokemon/'
      preLoaderRoute: typeof AuthenticatedPokemonIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pokemon/$id': {
      id: '/_authenticated/pokemon/$id'
      path: '/pokemon/$id'
      fullPath: '/pokemon/$id'
      preLoaderRoute: typeof AuthenticatedPokemonIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface NestedRouteRouteChildren {
  NestedCharmanderRoute: typeof NestedCharmanderRoute
  NestedPikachuRoute: typeof NestedPikachuRoute
}

const NestedRouteRouteChildren: NestedRouteRouteChildren = {
  NestedCharmanderRoute: NestedCharmanderRoute,
  NestedPikachuRoute: NestedPikachuRoute,
}

const NestedRouteRouteWithChildren = NestedRouteRoute._addFileChildren(
  NestedRouteRouteChildren,
)

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedPokemonIdRoute: typeof AuthenticatedPokemonIdRoute
  AuthenticatedPokemonIndexRoute: typeof AuthenticatedPokemonIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedPokemonIdRoute: AuthenticatedPokemonIdRoute,
  AuthenticatedPokemonIndexRoute: AuthenticatedPokemonIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NestedRouteRoute: NestedRouteRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
